### ISSUE TITLE
Insert command tracing disabling.

### ISSUE THREAD

**Issue by JakeSmokie** [blushingpenguin/MongoDB.ApplicationInsights#1]
Is it possible to disable insert command output?
As I see AppInsights service gets all data which is inserted in Mongo, which is an unwanted behavior.

![image](https://user-images.githubusercontent.com/14360046/65539430-179bc280-df12-11e9-8a53-8189087bc2cf.png)

**Comment by blushingpenguin** [comment]
You can add insert to FilteredCommands in MongoApplicationInsightsSettings with something like:

```csharp
var settings = new MongoApplicationInsightsSettings();
settings.FilteredCommands.Add("insert");
var factory = new MongoClientFactory(settings: settings);
var client = factory.GetClient();
```

If you mean you want to log the insert but not the data, currently that's not supported, but I am certainly open to adding that functionality.

**Comment by JakeSmokie** [comment]
Temporarily I did these changes: 
https://github.com/JakeSmokie/MongoDB.ApplicationInsights/commit/dfbe73b9ee7466bc7ef97a296cb9b5240268005f#diff-e162235051fb88ff9fda82d49dd33228R90

**Comment by milkshakeuk** [comment]
@JakeSmokie you should be able to disable logging the commands now thanks to #5
