### ISSUE TITLE
End to End Transaction - Incorrect nesting

### ISSUE THREAD

**Issue by milkshakeuk** [blushingpenguin/MongoDB.ApplicationInsights#3]
Hi,

Thank you for this nuget package it has helped us capture MongoDb calls in our application insights.

I have come across an issue where the nesting of end to end transaction event list is not nested correctly in the timeline, possibly related to parentId on the events.

See image below.

![image](https://user-images.githubusercontent.com/1087376/84252254-42f92880-ab06-11ea-8ff1-afceb175d3da.png)

**Comment by milkshakeuk** [comment]
https://github.com/blushingpenguin/MongoDB.ApplicationInsights/blob/96a206c8056e35d183584aeb64258d2af3521176/MongoDB.ApplicationInsights/MongoApplicationInsightsTelemetry.cs#L108

I think this should be 
```c#
telemetry.Context.Operation.ParentId = activity.Id; 
```

after reading [some docs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation#data-model-for-telemetry-correlation).

"Every outgoing operation, such as an HTTP call to another component, is represented by dependency telemetry. Dependency telemetry also defines its own `id` that's globally unique. Request telemetry, initiated by this dependency call, uses this `id` as its `operation_parentId`."

also notice this:

https://github.com/microsoft/ApplicationInsights-dotnet/blob/5ac6bb98d04b7da6d151c0338efece4c124c750a/WEB/Src/DependencyCollector/DependencyCollector/Implementation/SqlClientDiagnostics/SqlClientDiagnosticSourceListener.cs#L364

**Comment by milkshakeuk** [comment]
@blushingpenguin once a new nuget package has been released this can be closed.

**Comment by milkshakeuk** [comment]
@blushingpenguin 
#4 doesnt fix this afteral but after doing some testing I think I have figured out why, will create new PR shortly.

**Comment by milkshakeuk** [comment]
@blushingpenguin 
#4 doesnt fix this afteral but after doing some testing I think I have figured out why, will create new PR shortly.

**Comment by milkshakeuk** [comment]
@blushingpenguin I wonder if you could have a look at this PR please 😊.

**Comment by blushingpenguin** [comment]
now merged, sorry for the delay

**Comment by milkshakeuk** [comment]
@blushingpenguin FYI nesting seems to be working fine on the Azure Portal for End-to-end transaction details. 👍
