### ISSUE TITLE
Too many open connections after using MongoDB.ApplicationInsights

### ISSUE THREAD

**Issue by psmorandi** [blushingpenguin/MongoDB.ApplicationInsights#7]
Hello there,

Last week we released a new version of one of our services with this library to get more info about the usage of MongoDB. This apps runs in our kubernetes cluster and our MongoDB is a [mongodb as a service](https://cloud.mongodb.com). We didn't see any problems at first, everything apparently was working as intended. After a while I notice that this service was OOMKilled a lot of times during the week after the release (in simple terms, the container was rebooted because it used more memory than we allowed it to have). So we put the threshold bigger, and today, for our surprise we got notified by MongoDB that our connection limit reached 80% of the limit, than after some minutes close to 100%. Only thing we did in this deploy was to add this library to help us with the Application Insights metrics.

So here are some charts that I got from the MongoDB. You can see that from 12 of setember there was a peak of commands with is followed with peak of connections:
![mongodb-operations](https://user-images.githubusercontent.com/3630061/93369923-71ce1b80-f826-11ea-9542-235082e0bd6c.png)
![mongodb-connections](https://user-images.githubusercontent.com/3630061/93370040-9e823300-f826-11ea-9788-f1f3fc33aabf.png)

The pikes and the valleys is because as the connections go up, memory consumption goes up, than the pod is killed and restarted, than goes again. Each chart is from one server in our replica set. After we removed the use of library:
![mongodb-operations-connections](https://user-images.githubusercontent.com/3630061/93370419-2d8f4b00-f827-11ea-89e0-7acbc5bfb13b.png)

So, this is the expected number of connections, we don't have a huge MongoDb use yet, these ones are shared instances since it's cheaper and it's ok for us.

I checked the library implementation and didn't find any reason for this, so maybe the way we are configuring it is wrong. This is what we have configured:

```c#
.AddSingleton<IMongoClientFactory>(
    sp => new MongoClientFactory(
         sp.GetService<TelemetryClient>(),
         new MongoApplicationInsightsSettings()
))
```
We use repository pattern and all references are used as `AddScoped`. If needed I can post all. We use this `IMongoClientFactory` in our `MongoDatabaseProvider` (we need the `SslProtocols.Tls12` to connect to mongo):

```c#
namespace Some.NameSpace
{
    using System;
    using System.Security.Authentication;
    using Configuration;
    using global::MongoDB.Driver;

    // this class is added as scoped
    public class MongoDatabaseProvider : IDataBaseProvider<IMongoDatabase>
    {
        public MongoDatabaseProvider(IMongoDbSettings settings, IMongoClientFactory mongoClientFactory)
        {
            this.Settings = settings ?? throw new ArgumentNullException(nameof(settings));
            if (!settings.UseSsl)
            {
                this.Client = new MongoClient(settings.ConnectionString);
            }
            else
            {
                var mongodbSettings = MongoClientSettings.FromUrl(
                    new MongoUrl(settings.ConnectionString)
                );

                mongodbSettings.SslSettings = new SslSettings { EnabledSslProtocols = SslProtocols.Tls12 };
                // this factory already tests if there is application insights configuration
                this.Client = mongoClientFactory?.GetClient(mongodbSettings) ?? new MongoClient(mongodbSettings);
            }
        }

        private IMongoClient Client { get; }
        private IMongoDbSettings Settings { get; }
        public IMongoDatabase GetDatabase()
        {
            return this.Client.GetDatabase(this.Settings.Database);
        }
    }
}
```
Can someone have a look if we did something wrong? Maybe we cant register the factory as singleton?

**Comment by milkshakeuk** [comment]
@psmorandi If you are using Aspnet Core there is a handy extension method you can use in the `Startup.cs` class in the `ConfigureServices` method.

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddHttpClient();
    services.AddMongoClientFactory(); // this will add the client factory as a singleton for you.
...
```

FYI when you use the `IMongoClientFactory` and call `GetClient` it will return a new instance of the mongo client every time.
If I were you I would register your `MongoDatabaseProvider` as a singleton in the IOC container, I'm guessing this will solve your problem.

The recommended approach for mongo is to have a single `MongoClient`.

http://mongodb.github.io/mongo-csharp-driver/2.11/reference/driver/connecting/#re-use

> It is recommended to store a MongoClient instance in a global place, either as a static variable or in an IoC container with a singleton lifetime.

**Comment by milkshakeuk** [comment]
@blushingpenguin @psmorandi 
Can this be closed? I suspect multiple `MongoClient` instances at play based on how @psmorandi described his setup.

**Comment by psmorandi** [comment]
Hello there, I guess you can close. We didn't have time to test it yet. We're finishing a new version, so after that we will try this. The @milkshakeuk answer makes sense and if anything goes wrong I could reopen this issue.

**Comment by blushingpenguin** [comment]
Sounds plausible, thanks for digging into it
