### ISSUE TITLE
Allow subscribing Mongo events from calling application

### ISSUE THREAD

**Issue by gkello** [blushingpenguin/MongoDB.ApplicationInsights#9]
Currently the MongoDB.ApplicationInsights is overriding clientSettings.ClusterConfigurator so that calling application is not able to subscribe to Mongo DB events.

See https://github.com/blushingpenguin/MongoDB.ApplicationInsights/pull/8 for fix.

P.S: build is failing with     

HTTP 400
Provided token is not a UUID.
Command executed with exception: 

when uploading data to https://codecov.io/

**Comment by blushingpenguin** [comment]
merged + fixed the upload, thanks
